### ISSUE TITLE
Exception when inserting new array type if array component type is from the same package

### ISSUE THREAD

**Issue by topnessman** [typetools/annotation-tools#155]
Minimum Testcase:
`A.java`
```java
package test;

public class A {
    static void foo() {
        B result[] = new B[2];
    }
}
```
`B.java`
```java
package test;

public class B {}
```
`default.jaif`
```
package qual:
  annotation @Q:

package test:
class B:

package test:
class A:
method foo()V:
insert-annotation Method.body, Block.statement 0, Variable.type: @qual.Q
insert-annotation Method.body, Block.statement 0, Variable.type, ArrayType.type: @qual.Q
insert-annotation Method.body, Block.statement 0, Variable.initializer, NewArray.type 0: @qual.Q
```
I ran:
```
../annotation-tools/annotation-file-utilities/scripts/insert-annotations-to-source default.jaif testinput/inference/limited-inferrable-afu/A.java testinput/inference/limited-inferrable-afu/B.java -v
```
Then I got exception:
```
Warning: IndexFileSpecification did not find classfile for: test.B
Warning: IndexFileSpecification did not find classfile for: test.A
Read 4 annotations from default.jaif
Processing testinput/inference/limited-inferrable-afu/A.java
Parsed testinput/inference/limited-inferrable-afu/A.java
Exception in thread "main" java.lang.Error
	at annotator.find.Insertions$TypeTree.javacTypeToType(Insertions.java:1357)
	at annotator.find.Insertions$TypeTree.javacTypeToType(Insertions.java:1296)
	at annotator.find.Insertions$TypeTree.fromJavacType(Insertions.java:1289)
	at annotator.find.Insertions.organizeTypedInsertions(Insertions.java:318)
	at annotator.find.Insertions.forClass(Insertions.java:148)
	at annotator.find.Insertions.forOuterClass(Insertions.java:128)
	at annotator.find.TreeFinder.getPositions(TreeFinder.java:1872)
	at annotator.Main.main(Main.java:710)
```

Can any of you see why there is exception? Thanks!

**Comment by topnessman** [comment]
@mernst @wmdietl

**Comment by wmdietl** [comment]
I can only reproduce this problem when I do not put the classes in the correct locations.
In this example, when I put `A.java` and `B.java` in a `test` directory, to correspond to the package declaration, everything works out.
If I put the example files in an incorrect layout, I get the error you describe.

In https://github.com/typetools/annotation-tools/commit/806c49091091e20462b28fa219ce01367ed79740 I've improved the error message that is raised.
I don't see a way to work around such setup problems.

Can you check whether there is something in your project layout that doesn't align with the corresponding package declarations?
